# Generated by Django 4.2.2 on 2023-06-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
