# Generated by Django 4.2.2 on 2023-07-06 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploadedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIs.organization'),
        ),
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='fileReq/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIs.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.individual')),
            ],
        ),
    ]
