# Generated by Django 4.2.2 on 2023-06-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_individual_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
