# Generated by Django 4.2.2 on 2023-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_files_uploadedby_filerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='name',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
