# Generated by Django 4.2.2 on 2023-07-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_filerequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='uploadedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APIs.organization'),
        ),
    ]
