# Generated by Django 4.2.2 on 2023-06-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_individual_created_at_organization_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
    ]
