# Generated by Django 4.2.2 on 2023-06-21 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_remove_individual_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
