# Generated by Django 4.2.2 on 2023-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0007_alter_individual_id_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
